-- Seed entities and checkpoints from checkpoints_data.json
-- Run after create-schema (and migrate-execution-stage if DB existed before).
-- sqlite3 data/ce_df_photos.db < scripts/create_entity_checkpoints.sql

INSERT OR IGNORE INTO entities (name, code, display_order) VALUES ('Trench', 'TRE', 0);
INSERT OR IGNORE INTO entities (name, code, display_order) VALUES ('Duct', 'DUC', 0);
INSERT OR IGNORE INTO entities (name, code, display_order) VALUES ('Joint/Loop HH', 'JOI', 0);
INSERT OR IGNORE INTO entities (name, code, display_order) VALUES ('Cable', 'CAB', 0);
INSERT OR IGNORE INTO entities (name, code, display_order) VALUES ('JC', 'JCX', 0);
INSERT OR IGNORE INTO entities (name, code, display_order) VALUES ('Route', 'ROU', 0);
INSERT OR IGNORE INTO entities (name, code, display_order) VALUES ('ROW', 'ROW', 0);

INSERT OR IGNORE INTO checkpoints (entity_id, checkpoint_name, code, display_order, evidence_type, execution_stage, execution_before, execution_ongoing, execution_after, photo_type) SELECT e.id, 'Trench Depth', 'TRE', 0, 'Photo', 'Ongoing', 0, 1, 0, 1 FROM entities e WHERE e.name = 'Trench' LIMIT 1;
INSERT OR IGNORE INTO checkpoints (entity_id, checkpoint_name, code, display_order, evidence_type, execution_stage, execution_before, execution_ongoing, execution_after, photo_type) SELECT e.id, 'Trench Depth (1)', 'TRE', 0, 'Photo', 'After', 0, 0, 1, 3 FROM entities e WHERE e.name = 'Trench' LIMIT 1;
INSERT OR IGNORE INTO checkpoints (entity_id, checkpoint_name, code, display_order, evidence_type, execution_stage, execution_before, execution_ongoing, execution_after, photo_type) SELECT e.id, 'Protection', 'PRO', 0, 'Photo', 'After', 0, 0, 1, 2 FROM entities e WHERE e.name = 'Trench' LIMIT 1;
INSERT OR IGNORE INTO checkpoints (entity_id, checkpoint_name, code, display_order, evidence_type, execution_stage, execution_before, execution_ongoing, execution_after, photo_type) SELECT e.id, 'No of Duct', 'NOO', 0, 'Photo', 'Ongoing', 0, 1, 0, 1 FROM entities e WHERE e.name = 'Trench' LIMIT 1;
INSERT OR IGNORE INTO checkpoints (entity_id, checkpoint_name, code, display_order, evidence_type, execution_stage, execution_before, execution_ongoing, execution_after, photo_type) SELECT e.id, 'HDD Entry Exit Point', 'HDD', 0, 'Photo', 'Ongoing', 0, 1, 0, 3 FROM entities e WHERE e.name = 'Trench' LIMIT 1;
INSERT OR IGNORE INTO checkpoints (entity_id, checkpoint_name, code, display_order, evidence_type, execution_stage, execution_before, execution_ongoing, execution_after, photo_type) SELECT e.id, 'Clamping', 'CLA', 0, 'Photo', 'After', 0, 0, 1, 1 FROM entities e WHERE e.name = 'Trench' LIMIT 1;
INSERT OR IGNORE INTO checkpoints (entity_id, checkpoint_name, code, display_order, evidence_type, execution_stage, execution_before, execution_ongoing, execution_after, photo_type) SELECT e.id, 'Barricading', 'BAR', 0, 'Photo', 'Ongoing', 0, 1, 0, 1 FROM entities e WHERE e.name = 'Trench' LIMIT 1;
INSERT OR IGNORE INTO checkpoints (entity_id, checkpoint_name, code, display_order, evidence_type, execution_stage, execution_before, execution_ongoing, execution_after, photo_type) SELECT e.id, 'PPE', 'PPE', 0, 'Photo', 'Ongoing', 0, 1, 0, 1 FROM entities e WHERE e.name = 'Trench' LIMIT 1;
INSERT OR IGNORE INTO checkpoints (entity_id, checkpoint_name, code, display_order, evidence_type, execution_stage, execution_before, execution_ongoing, execution_after, photo_type) SELECT e.id, 'Crossing Protection', 'CRO', 0, 'Photo', 'Ongoing', 0, 1, 1, 3 FROM entities e WHERE e.name = 'Trench' LIMIT 1;
INSERT OR IGNORE INTO checkpoints (entity_id, checkpoint_name, code, display_order, evidence_type, execution_stage, execution_before, execution_ongoing, execution_after, photo_type) SELECT e.id, 'Deviation if applicable', 'DEV', 0, 'Approval Mail', 'Ongoing', 0, 0, 0, NULL FROM entities e WHERE e.name = 'Trench' LIMIT 1;
INSERT OR IGNORE INTO checkpoints (entity_id, checkpoint_name, code, display_order, evidence_type, execution_stage, execution_before, execution_ongoing, execution_after, photo_type) SELECT e.id, 'No Of Duct', 'NOO', 0, 'Photo', 'Ongoing', 0, 1, 0, 1 FROM entities e WHERE e.name = 'Duct' LIMIT 1;
INSERT OR IGNORE INTO checkpoints (entity_id, checkpoint_name, code, display_order, evidence_type, execution_stage, execution_before, execution_ongoing, execution_after, photo_type) SELECT e.id, 'Duct Coupler', 'DUC', 0, 'Photo', 'Ongoing', 0, 1, 0, 1 FROM entities e WHERE e.name = 'Duct' LIMIT 1;
INSERT OR IGNORE INTO checkpoints (entity_id, checkpoint_name, code, display_order, evidence_type, execution_stage, execution_before, execution_ongoing, execution_after, photo_type) SELECT e.id, 'Joint and Loop HH  Photo', 'JOI', 0, 'Photo', 'Ongoing', 0, 1, 1, 4 FROM entities e WHERE e.name = 'Joint/Loop HH' LIMIT 1;
INSERT OR IGNORE INTO checkpoints (entity_id, checkpoint_name, code, display_order, evidence_type, execution_stage, execution_before, execution_ongoing, execution_after, photo_type) SELECT e.id, 'Duct Entry', 'DUC', 0, 'Photo', 'Ongoing', 0, 1, 0, 1 FROM entities e WHERE e.name = 'Joint/Loop HH' LIMIT 1;
INSERT OR IGNORE INTO checkpoints (entity_id, checkpoint_name, code, display_order, evidence_type, execution_stage, execution_before, execution_ongoing, execution_after, photo_type) SELECT e.id, 'Cable Loop', 'CAB', 0, 'Photo', 'After', 0, 0, 1, 1 FROM entities e WHERE e.name = 'Joint/Loop HH' LIMIT 1;
INSERT OR IGNORE INTO checkpoints (entity_id, checkpoint_name, code, display_order, evidence_type, execution_stage, execution_before, execution_ongoing, execution_after, photo_type) SELECT e.id, 'Simplex/End Plug', 'SIM', 0, 'Photo', 'After', 0, 0, 1, 1 FROM entities e WHERE e.name = 'Joint/Loop HH' LIMIT 1;
INSERT OR IGNORE INTO checkpoints (entity_id, checkpoint_name, code, display_order, evidence_type, execution_stage, execution_before, execution_ongoing, execution_after, photo_type) SELECT e.id, 'Cable Id', 'CAB', 0, 'Photo', 'After', 0, 0, 1, 1 FROM entities e WHERE e.name = 'Joint/Loop HH' LIMIT 1;
INSERT OR IGNORE INTO checkpoints (entity_id, checkpoint_name, code, display_order, evidence_type, execution_stage, execution_before, execution_ongoing, execution_after, photo_type) SELECT e.id, 'Deviation if applicable', 'DEV', 0, 'Approval Mail', 'Ongoing', 0, 0, 0, NULL FROM entities e WHERE e.name = 'Joint/Loop HH' LIMIT 1;
INSERT OR IGNORE INTO checkpoints (entity_id, checkpoint_name, code, display_order, evidence_type, execution_stage, execution_before, execution_ongoing, execution_after, photo_type) SELECT e.id, 'OTDR Trace report', 'OTD', 0, 'Doc', 'After', 0, 0, 1, NULL FROM entities e WHERE e.name = 'Cable' LIMIT 1;
INSERT OR IGNORE INTO checkpoints (entity_id, checkpoint_name, code, display_order, evidence_type, execution_stage, execution_before, execution_ongoing, execution_after, photo_type) SELECT e.id, 'Splice Tray', 'SPL', 0, 'Photo', 'After', 0, 0, 1, 1 FROM entities e WHERE e.name = 'JC' LIMIT 1;
INSERT OR IGNORE INTO checkpoints (entity_id, checkpoint_name, code, display_order, evidence_type, execution_stage, execution_before, execution_ongoing, execution_after, photo_type) SELECT e.id, 'Cable Entry point in closure sealed', 'CAB', 0, 'Photo', 'After', 0, 0, 1, 1 FROM entities e WHERE e.name = 'JC' LIMIT 1;
INSERT OR IGNORE INTO checkpoints (entity_id, checkpoint_name, code, display_order, evidence_type, execution_stage, execution_before, execution_ongoing, execution_after, photo_type) SELECT e.id, 'Cable Tag', 'CAB', 0, 'Photo', 'After', 0, 0, 1, 1 FROM entities e WHERE e.name = 'JC' LIMIT 1;
INSERT OR IGNORE INTO checkpoints (entity_id, checkpoint_name, code, display_order, evidence_type, execution_stage, execution_before, execution_ongoing, execution_after, photo_type) SELECT e.id, 'Punch Point  rectification', 'PUN', 0, 'Doc', 'Before', 1, 0, 1, 2 FROM entities e WHERE e.name = 'Route' LIMIT 1;
INSERT OR IGNORE INTO checkpoints (entity_id, checkpoint_name, code, display_order, evidence_type, execution_stage, execution_before, execution_ongoing, execution_after, photo_type) SELECT e.id, 'AT Documents', 'ATD', 0, 'Doc', 'After', 0, 0, 1, NULL FROM entities e WHERE e.name = 'Route' LIMIT 1;
INSERT OR IGNORE INTO checkpoints (entity_id, checkpoint_name, code, display_order, evidence_type, execution_stage, execution_before, execution_ongoing, execution_after, photo_type) SELECT e.id, 'Application', 'APP', 0, 'Doc', 'After', 0, 0, 1, NULL FROM entities e WHERE e.name = 'ROW' LIMIT 1;
INSERT OR IGNORE INTO checkpoints (entity_id, checkpoint_name, code, display_order, evidence_type, execution_stage, execution_before, execution_ongoing, execution_after, photo_type) SELECT e.id, 'DN', 'DNX', 0, 'Doc', 'After', 0, 0, 1, NULL FROM entities e WHERE e.name = 'ROW' LIMIT 1;
INSERT OR IGNORE INTO checkpoints (entity_id, checkpoint_name, code, display_order, evidence_type, execution_stage, execution_before, execution_ongoing, execution_after, photo_type) SELECT e.id, 'Payment Receipt', 'PAY', 0, 'Doc', 'After', 0, 0, 1, NULL FROM entities e WHERE e.name = 'ROW' LIMIT 1;
INSERT OR IGNORE INTO checkpoints (entity_id, checkpoint_name, code, display_order, evidence_type, execution_stage, execution_before, execution_ongoing, execution_after, photo_type) SELECT e.id, 'Permit Copy', 'PER', 0, 'Doc', 'After', 0, 0, 1, NULL FROM entities e WHERE e.name = 'ROW' LIMIT 1;
